# this workflow runs in master but, for now, executes bash and python scripts in "abranch" that read data from knack and discord 
# and create a servable file (members.json) on knack. it should also update knack if/as needed
name: BUILDMEMBERDATA

# Controls when the action will run. Triggers the workflow manually only
on:
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
   #needs to be name of branch we run on. in production will be main branch so we will leave this out
         ref: abranch
         
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'


    # Runs a set of commands using the runners shell
       
    - name: Run a multi-line script
      env:
         DISCORD_CODE: ${{ secrets.YAK_DISCORD_CODE }}
         KNACK_APPID: ${{ secrets.KNACK_APPID }}
         KNACK_CODE: ${{ secrets.KNACK_CODE }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -x
        set -v
        echo before
        bash bashscript
        echo "between bash and python"
        python -c "print('ahha')"
        echo "after test python"
        python $GITHUB_WORKSPACE/pythonfile.py $DISCORD_CODE $KNACK_APPID $KNACK_CODE $GITHUB_TOKEN $GITHUB_WORKSPACE
        echo also after
    - name: 'create artifact'
      uses: 'actions/upload-artifact@v2'
      with:
              path: 'members.json'
    - name: 'update file with link file'
      run: |
          echo "members.json" > .gitignore
          git config user.name tilnow
          git config user.email tilnowah@gmail.com
          git add .
          git commit -m "updated linktomembers"
          git push  
