# This is a test workflow, trying to be in a branch. using same names as in main branch

name: TESTBRANCHES

# Controls when the action will run. Triggers the workflow manually only
on:
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
         ref: abranch
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'


    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo null
        cat $GITHUB_WORKSPACE/afile
        echo "did i create a file" > $GITHUB_WORKSPACE/alsoafile
        python $GITHUB_WORKSPACE/pythonfile.py
        echo also null
