# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2



    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        curl "https://api.github.com/repos/tilnow/testbot/issues/1/reactions" -H "Accept: application/vnd.github.squirrel-girl-preview" | grep "\"content\":" > tmp.txt
        echo "and now"
        cat tmp.txt
        echo "+1"
        cat tmp.txt | grep "\+1" | wc -l
        tplus=$(cat tmp.txt | grep "\+1" | wc -l)
        echo "-1"
        cat tmp.txt | grep "\-1" | wc -l
        tminus=$(cat tmp.txt | grep "\-1" | wc -l)
        let diff=tplus-tminus
        echo $diff
        [ diff -gt 1] && echo "we have a winner"
        echo "after cat"
        curl "https://api.github.com/repos/tilnow/testbot/issues/0" | grep -m 1 -Po '"number":.*?[^\\]",' 

