# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2



    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        set -v
        set -x
        #curl "https://api.github.com/repos/tilnow/testbot/issues" | grep -o -m 1 '"number": [0-9]*' | sed 's/^.*: //'
        let issuenum=$(curl "https://api.github.com/repos/tilnow/testbot/issues" | grep -o -m 1 '"number": [0-9]*' | sed 's/^.*: //' )
        echo "number of issues:" $issuenum
        for i in `seq 1 $issuenum`;
        do
        echo "https://api.github.com/repos/tilnow/testbot/issues/${i}/reactions"
        echo "skip grep"
        echo "stm" >atmp.txt
        curl "https://api.github.com/repos/tilnow/testbot/issues/${i}/reactions" -H "Accept: application/vnd.github.squirrel-girl-preview" >>atmp.txt
        echo "atmp" 
        cat atmp.txt
        grep "\"content\":" <atmp.txt
        echo "now try and fail with rec"
        rec=$(curl "https://api.github.com/repos/tilnow/testbot/issues/${i}/reactions" -H "Accept: application/vnd.github.squirrel-girl-preview")
        echo $rec
        [ -z "$rec" ] && echo "Empty" || echo "Not empty"
        echo "now try to grep variable"
        echo $rec | grep "\"content\":" > tmp.txt
        echo "and now with grep"
        curl "https://api.github.com/repos/tilnow/testbot/issues/${i}/reactions" -H "Accept: application/vnd.github.squirrel-girl-preview" | grep "\"content\":" 
        echo "and now with >"
        curl "https://api.github.com/repos/tilnow/testbot/issues/${i}/reactions" -H "Accept: application/vnd.github.squirrel-girl-preview" | grep "\"content\":" > tmp.txt
        echo "and now"
        cat tmp.txt
        echo "+1"
        cat tmp.txt | grep "\+1" | wc -l
        tplus=$(cat tmp.txt | grep "\+1" | wc -l)
        echo "-1"
        cat tmp.txt | grep "\-1" | wc -l
        tminus=$(cat tmp.txt | grep "\-1" | wc -l)
        let diff=tplus-tminus
        echo $diff
        [ $diff -gt 1 ] && echo "we have a winner"
        echo "after cat"
        
        done
        curl   -X POST   -H "Accept: application/vnd.github.v3+json" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/tilnow/testbot/issues/1/labels  -d '{"labels":["bug"]}'

